### ISSUE TITLE
Loading Proteus AMP models gives no effect?

### ISSUE THREAD

**Issue by webaake** [AidaDSP/AIDA-X#18] opened 2023-04-14 07:08 UTC
I've compiled AIDA_-X from source and compilation seemed OK, no errors. The plugin loads in Reaper and looks fine and the knobs work. It does give a bit of a tube warmth sound to guitar. But, none of the Proteus Amp-model files affects the sound at all. (Button is activated). Same with the Deer Ink models. 

The models make a HUGE difference in Proteus, so they work in them selves. 

So far I've tried the CLAP and VST3 versions of the compiled plugin, but no luck with the sounds. 

What can I do? Do I miss some library even if it compiled okay? 

(I'll try the LV2 plugin as well)

This is on an updated Devuan Chimeara with Reaper 6.75. Jack is running. No pulseaudio or pipewire at all.

**Comment by webaake** [comment] 2023-04-14 10:09
Thx! Will test. But those from Deer Ink should work? Only two but...

**Comment by falkTX** [comment] 2023-04-14 10:38
They should yes, maybe the sound is just too similar? The Deer Ink ones come by default.

There is a whole collection of models and people talking about it in https://forum.mod.audio/c/neural/62 by the way, you could try one of those.

**Comment by falkTX** [comment] 2023-04-14 20:25
did you get it to work?
there are quite a few on the MOD forums to try out, not as many as NAM has but our collection is growing quickly too.

**Comment by webaake** [comment] 2023-04-19 05:24
Thx FalkTX! Got some models from your links and they work fine. I also found your converted Proteus models and I'll try them out as well. Aida-X is really nice and looks nice too! Very very small on resources.

I miss one thing though, and that is if you load i model or IR file, I wish that Aida-X would remember that folder and then list the files in that folder. Maybe it's my Linux setup (DE) that spooks it? Using CLAP version.

**Comment by falkTX** [comment] 2023-04-19 09:12
> I miss one thing though, and that is if you load a model or IR file, I wish that Aida-X would remember that folder and then list the files in that folder. Maybe it's my Linux setup (DE) that spooks it? Using CLAP version.

This is already the case, but sadly some Linux desktops such as Gnome do not support such a feature (open dialogs always start with "recently opened files"). On KDE it behaves as intended from my experience, same on macOS and Windows.

We want to have a way to scroll through the list of files from a folder after picking one, but that is not coming for the 1.0 release.

In any case, the bug that this ticket relates to was invalid, loading models do work, so closing

**Closed by falkTX** 2023-04-19 09:12 UTC
